use_frameworks!

platform :ios, '10.0'

target 'MJRefreshHaptica_Example' do
  pod 'MJRefreshHaptica', :path => '../'

  target 'MJRefreshHaptica_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
